export const authType = {
    AUTH_REQUEST: "AUTH_REQUEST",
    AUTH_SUCCESS: "AUTH_SUCCESS",
    AUTH_FAILURE: "AUTH_FAILURE",
    AUTH_REGISTER_REQUEST: 'AUTH_REGISTER_REQUEST',
    AUTH_INITIAL_REQUEST: 'AUTH_INITIAL_REQUEST',
    AUTH_LOGOUT_REQUEST: 'AUTH_LOGOUT_REQUEST',
};