create table categories
(
    id          bigserial not null
        constraint categories_pkey
            primary key,
    category    varchar   not null,
    parent      bigint
        constraint categories_parent_fkey
            references categories
            on update cascade on delete set null,
    description text
);

alter table categories
    owner to postgres;

INSERT INTO public.categories (id, category, parent, description) VALUES (1, 'Artistica', null, 'La fotografía artística surge a mediados del siglo XIX. El lenguaje artístico fotográfico parte básicamente de la herencia de la pintura. La fotografía artística tiene un carácter muy subjetivo y la manipulación de las imágenes se ha convertido en algo indispensable para la expresión artística. Podemos destacar en este tipo de fotografía a Annie Leibovitz, Helmut Newton o David LaChapelle, fotógrafos que sin duda siguen formando parte de la evolución de la fotografía artística.');
INSERT INTO public.categories (id, category, parent, description) VALUES (2, 'Publicitaria', null, 'La fotografía publicitaria es uno de los tipos de fotografía más conocidos. Busca ser una imagen atractiva para el consumidor, siendo influyente en las ideas tanto políticas como sociales de la gente. Empezó a formar parte de la publicidad a partir de 1920 y desde entonces se ha convertido en un elemento clave.');
INSERT INTO public.categories (id, category, parent, description) VALUES (4, 'Moda', null, 'Con el paso del tiempo, la fotografía de moda ha desarrollado su propia estética donde en la imagen no prima solo la ropa, sino el maquillaje, el peinado, los accesorios y escenarios elegidos por el fotógrafo para crear una fotografía única. La fotografía de moda apareció por primera vez en publicaciones francesas como La Mode Practique. Tras la muerte de Richard Avedon, Irving Penn o Helmut Newton, los fotógrafos que destacan dentro de este tipo de fotografía son Mario Sorrenti, Mario Testino, Steven Maisel o Patrick Demarchelier entre muchos otros.');
INSERT INTO public.categories (id, category, parent, description) VALUES (5, 'Documental', null, 'A través de la fotografía documental se busca registrar e informar de distintos aspectos de la vida, formas y condiciones. Constituye una evidencia de la realidad. Este tipo de fotografía no se limita solo a los humanos, sino que puede tratar también sobre animales, naturaleza… Nace en los años 80-90 con Jacob Risk y Lewis W. Hine. Hay que destacar los nombres de Sebastiao Salgado, Cristina García Rodero, Dorothea Lange, Walker Evans, Boris Mikhaïlov… entre muchos otros.');
INSERT INTO public.categories (id, category, parent, description) VALUES (6, 'Retrato', null, 'Dentro de los distintos tipos de fotografía, el retrato fotográfico busca captar la esencia, la apariencia y los rasgos más característicos de la persona fotografiada. La fotografía de retrato surge casi a la vez que la invención de las cámaras, siendo un método muy accesible y barato para plasmar la imagen de una persona, como ya se hizo con la pintura de retrato. Existen variantes dentro de la fotografía de retrato donde pueden cambiar los planos (plano detalle, plano medio, primer plano, primerísimo primer plano…) y la luz (luz frontal, luz lateral, luz de relleno, luz de fondo…) Dentro del campo del retrato fotográfico podemos hacer mención a un subgénero conocido como la fotografía de difuntos. En este tipo de fotografía podemos destacar a Joel Santos, Steve McCurry, Jimmy Nelson, Lee Jeffries o Rehan entre otros.');
INSERT INTO public.categories (id, category, parent, description) VALUES (7, 'Periodistica', null, 'El fotoperiodismo es un género dentro del periodismo como tal que está directamente relacionado con la fotografía, el diseño gráfico y el vídeo. Se ha desarrollado sobre todo en los conflictos bélicos de distintas partes del mundo y ha sido vital para registrar la historia de acontecimientos como la Guerra Civil Española. Cabe destacar a Jacob Riis, Robert Capa, Henri Cartier-Bresson, Carl Mydans…');
INSERT INTO public.categories (id, category, parent, description) VALUES (8, 'Aerea', null, 'La fotografía aérea permite realizar fotografías a gran altura, dando lugar a imágenes increíbles de lugares como nunca antes las habrías visto de no ser por este tipo de fotografía. Desde comienzo del siglo XXI la fotografía aérea ha experimentado una evolución notoria gracias a la llegada de los drones y la fotografía con drones. Dentro de la fotografía aérea podemos destacar la fotografía orbital, es decir, fotografías del espacio a través de satélites en órbita en torno a la Tierra.');
INSERT INTO public.categories (id, category, parent, description) VALUES (9, 'Submarina', null, 'Dentro de los fotógrafos documentales de naturaleza, también destacan los fotógrafos de la naturaleza submarina. La fotografía submarina va ligada al buceo, también se puede realizar sin botella a una profundidad menor o incluso con snorkel, pero los resultados no serán los mismos. Es un tipo de fotografía bastante costoso, por un lado debido a la práctica de submarinismo para llevarla a cabo y por otro la compra del material fotográfico. Algo a tener en cuenta en la fotografía submarina es el color dependiendo de la inmersión: a 3 metros el rojo es pardo, los naranjas son amarillos y a partir de 15 metros todo es azul.');
INSERT INTO public.categories (id, category, parent, description) VALUES (10, 'Nocturna', null, 'La fotografía nocturna es una técnica muy recurrente. Los momentos idóneos para realizar este tipo de fotografía son el anochecer y el amanecer. Te dejamos el post que realizamos sobre la fotografía nocturna para que aprendas toda la técnica que debes llevar a cabo para obtener buenos resultados.');
INSERT INTO public.categories (id, category, parent, description) VALUES (11, 'Paisajes', null, 'La fotografía de paisajes apareció por primera vez en 1826 con Nicéphore Niépce y es una de las modalidades más complicadas. Para poder realizar una buena fotografía de paisaje en la que todos los elementos destaquen por igual, hay que hacer uso de varios objetivos distintos como el gran angular o el teleobjetivo y hay que tener en cuenta muchos elementos como la luz, la hora del día, el foco de atención…');
INSERT INTO public.categories (id, category, parent, description) VALUES (12, 'Astronomica', null, 'La fotografía astronómica se divide en dos campos: fotografía planetaria y fotografía de cielo profundo. En la fotografía planetaria, lo que se fotografía se encuentra dentro de nuestro Sistema Solar, mientras que en la de cielo profundo se fotografían objetos más allá de nuestro Sistema Solar (nebulosas, cúmulos estelares, supernovas…)');
INSERT INTO public.categories (id, category, parent, description) VALUES (13, 'Cientifica', null, 'Este tipo de fotografía se encarga de inmortalizar experimentos, representar información científica ajena al ojo humano que sin la fotografía científica no podría apreciar. Se vale de diferentes técnicas como la fotografía ultravioleta, la infrarroja, las imágenes térmicas o los rayos X. Otros instrumentos, como los microscopios electrónicos están equipados con mecanismos para tomar fotos o con adaptadores que permiten el empleo de una cámara normal.');
INSERT INTO public.categories (id, category, parent, description) VALUES (14, 'Fotomacrografia', null, 'Con esta fotografía podemos acercarnos tanto a los objetos y sujetos cotidianos que descubriremos multitud de detalles ajenos a nosotros hasta el momento en el que tomamos la foto. Consiste en tomar fotos de los objetos acercándose tanto que el tamaño del objeto en la película o en el sensor sea igual o superior al que tenga en la vida real. Podremos realizar este tipo de fotografía con el sensor macro.');