export const GET_ASYNC_REDUX_SAGA_PROP_TYPE = "GET_ASYNC_REDUX_SAGA_PROP_TYPE";
export const GET_ASYNC_REDUX_SAGA_PROP_TYPE_SUCCESS = "GET_ASYNC_REDUX_SAGA_PROP_TYPE_SUCCESS";
export const ASYNC_REDUX_SAGA_PROP_TEXT = "ASYNC_REDUX_SAGA_PROP_TEXT";